apiVersion: v1
kind: Service
metadata:
  name: {{ include "excalidraw.fullname" . }}-nginx
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 80
      {{- if .Values.nginx.service.nodePort }}
      nodePort: {{ .Values.nginx.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "excalidraw.name" . }}-nginx
