apiVersion: v1
kind: Service
metadata:
  name: {{ include "excalidraw.fullname" . }}-frontend
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "excalidraw.name" . }}-frontend
